### ISSUE TITLE
Documentation: add Paths type parameter to OpenAPIBuilder examples

### ISSUE THREAD

**Issue by timhanlon** [johannschopplich/apiverse#1]
Thanks for apiful!

It took me a bit to figure out I needed to add a second type parameter to `OpenAPIBuilder`.

Happy to open a PR to update the docs.

**Comment by johannschopplich** [comment]
Glad to hear!

Huh, actually you don't need to add a second parameter... What is your usage exactly? Can you please share an example?

When you have generated the types from your OpenAPI schema with `npx apiful generate`, you should be set up. 🤔 

Sure, PR always welcome!

**Comment by johannschopplich** [comment]
~~Closing this for now, as not intended.~~

**Comment by johannschopplich** [comment]
@timhanlon Sorry for the ping. Indeed, there was a bug in the last release! OMG, I wasn't aware. Fixed in v0.11.1.
